import { useEffect, useState, useMemo } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import { Header } from '../components/Header/Header'
import { Card } from '../components/Card/Card'
import { BigCard } from '../components/BigCard/BigCard'
import axios from 'axios'
import { Section } from '../components/Section/Section';
import { Testimonal } from '../components/Testimonal/Testimonal'
import { Footer } from '../components/Footer/Footer'
import { Loader } from '../components/Loader/Loader'


const cards = [
  {
    id: 1,
    name: "Nia",
    text: "“This task can be perfect for students from FIT”",
    imageUrl: "/user.png"
  },
  {
    id: 2,
    name: "Abigale",
    text: "“I am so sexy, that men are doing  test tasks for me for free.”",
    imageUrl: "/user.png"
  },
  {
    id: 3,
    name: "Fedya",
    text: "“Kuku Epta. EZ Task.”",
    imageUrl: "/user.png"
  },
];

const items = [
  {
    id: 1,
    name: "John Kennedy",
    text: "Wow, this test task is absolutely amazing! Loved it!",
    imageUrl: "/user.png",
    publishTime: "05:20",
    rating: 4,
  },
  {
    id: 2,
    name: "John Kennedy",
    text: "Wow, this test task is absolutely amazing! Loved it!",
    imageUrl: "/user.png",
    publishTime: "05:20",
    rating: 2,
  },
 
];

const URL = '/api/hello';

export default function Home() {
  const [data, setData] = useState(null);

  const fetchItems = () => {
    axios.post(URL).then((res) => setData(res.data)).catch(e => console.log(e))
  }

  useEffect( () => {
    fetchItems()
  }, [])

  const btcData = data ? Math.trunc(+data?.btc.ticker.price) : '0000';
  const ethData = data ? Math.trunc(+data?.eth.ticker.price) : '-';

  // if (!data) return <Loader />;
  
  return (
    <div className={styles.mainContainer}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
       
      </Head>

      <Header />

      { data ? 

        <main className={styles.main}>

          <div className={styles.mainText}>
              Do The Task And Have Fun
          </div>
          
          <div className={styles.secondaryText}>
            Be Persistent & Attentive To Details
          </div>

          <div className={styles.cardWrapper}>
            <Card 
              showPosition
              cardText={`“The Style Of This Test Task
              Matches The Style That You Will
              Be Making Real Job In.”`}
              cardPosition="Head Of UX Design"
              cardName="Andy"
            
            />

            <BigCard 
              btc={btcData}
              eth={ethData}
            />
          </div>

          <Section
            title="What Pros Are Saying..."
          >
            {cards.map(card => (
                <Card 
                  key={card.id}
                  cardName={card.name} 
                  cardText={card.text} 
                  imageUrl={card.imageUrl} 
                />
            ))}

          </Section>

          <Section
            title="What Other Coders Are Saying..."
            flexColumn
          >
            {items.map(card => (
                <Testimonal 
                  key={card.id}
                  cardName={card.name} 
                  cardText={card.text} 
                  imageUrl={card.imageUrl}
                  rating={card.rating}
                />
            ))}

          </Section>
          <Footer />
        </main>

        : <Loader />
      }
  
    </div>
  )
}
